language: dart
sudo: false
dart: dev

dart_task:
  - test: --platform vm
  - test: --platform firefox -j 1
  - dartanalyzer --fatal-infos --fatal-warnings

matrix:
  include:
    - dart: dev
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
