name: web_socket_channel
version: 1.2.0

description: >-
  StreamChannel wrappers for WebSockets. Provides a cross-platform
  WebSocketChannel API, a cross-platform implementation of that API that
  communicates over an underlying StreamChannel.
homepage: https://github.com/dart-lang/web_socket_channel

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  async: ">=1.3.0 <3.0.0"
  crypto: ">=0.9.2 <4.0.0"
  stream_channel: ">=1.2.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.16.0-nullsafety
