name: web_socket_channel
version: 3.0.0
description: Cross-platform StreamChannel wrappers for WebSocket connections.
repository: https://github.com/dart-lang/web_socket_channel

environment:
  sdk: ^3.2.0

dependencies:
  async: ^2.5.0
  crypto: ^3.0.0
  stream_channel: ^2.1.0
  web: ^0.4.0

dev_dependencies:
  dart_flutter_team_lints: ^2.0.0
  test: ^1.16.0
