name: web_socket_channel
version: 3.0.1-wip
description: >-
  StreamChannel wrappers for WebSockets. Provides a cross-platform
  WebSocketChannel API, a cross-platform implementation of that API that
  communicates over an underlying StreamChannel.
repository: https://github.com/dart-lang/web_socket_channel

environment:
  sdk: ^3.3.0

dependencies:
  async: ^2.5.0
  crypto: ^3.0.0
  stream_channel: ^2.1.0
  web: ^0.5.0
  web_socket: ^0.1.3

dev_dependencies:
  dart_flutter_team_lints: ^3.0.0
  test: ^1.25.2
