name: web_socket_channel
# need to bump pkg:test to support v2 before we release!
version: 1.3.0-dev

description: >-
  StreamChannel wrappers for WebSockets. Provides a cross-platform
  WebSocketChannel API, a cross-platform implementation of that API that
  communicates over an underlying StreamChannel.
repository: https://github.com/dart-lang/web_socket_channel

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  async: ^2.5.0
  crypto: ^3.0.0
  stream_channel: ^2.1.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
